/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgetplanner;


import java.awt.Color;

import javax.media.Manager;

import javax.media.Player;
import java.io.File;


/**
 *
 * @author ASUS
 */

public class FlashForm extends javax.swing.JFrame implements Runnable
{

   
 /**
     * Creates new form FlashForm
     */
    
public FlashForm() 
{
        initComponents();

    getContentPane().setBackground(Color.white);
    Thread thread=new Thread(this);
//this:current class reference

        thread.start();
 
   }

//    @Override

    public void run()
  
  {
     
   try
   
     {

       Player play=Manager.createRealizedPlayer(new File("E:\\Java\\Documents\\NetBeansProjects\\BudgetPlanner//src//budgetplanner//39482028.wav").toURI().toURL());

            play.start();

  for(int i=0;i<100;i++)

 {
 
  jProgressBar1.setValue(i);

                Thread.sleep(60);

            }
 
           play.stop();

            
//            LoginPage lP=new LoginPage();

//            lP.setVisible(true);

            dispose();

        }
catch(Exception ex){}

    }

 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents()
 {

   
     jProgressBar1 = new javax.swing.JProgressBar();

        jLabel1 = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setBackground(new java.awt.Color(255, 255, 255));
 
       setUndecorated(true);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));

        jProgressBar1.setForeground(new java.awt.Color(102, 102, 102));

        jProgressBar1.setBorder(new javax.swing.border.MatteBorder(null));

        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jProgressBar1.setOpaque(true);

        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 310, 30));


        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java\\Documents\\Media\\6dd3f32a5b2088118cf2d5de993f8833.jpg"));
 // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));


        pack();

       setLocationRelativeTo(null);

    }
// </editor-fold>//GEN-END:initComponents


   /**
     * @param args the command line arguments
     */

    public static void main(String args[])
 {
        
/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
*/
        
try 
{
            
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
 {
    
  if ("Nimbus".equals(info.getName()))
 {
                    
javax.swing.UIManager.setLookAndFeel(info.getClassName());

 break;
                
}
}
}
 catch (ClassNotFoundException ex)
 {
 
 java.util.logging.Logger.getLogger(FlashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } 
catch (InstantiationException ex)
 {
            
java.util.logging.Logger.getLogger(FlashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 
       }
 catch (IllegalAccessException ex)
 {
            
java.util.logging.Logger.getLogger(FlashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 
       } 
catch (javax.swing.UnsupportedLookAndFeelException ex)
{
            
java.util.logging.Logger.getLogger(FlashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        /* Create and display the form */
    
    java.awt.EventQueue.invokeLater(new Runnable()
 {
     
       public void run()
 {
                
new FlashForm().setVisible(true);

  }
});
  
  }

 
   // Variables declaration - do not modify//GEN-BEGIN:variables
 
   private javax.swing.JLabel jLabel1;
 
   private javax.swing.JProgressBar jProgressBar1;

    // End of variables declaration//GEN-END:variables

}
